[project]
name = "voiceai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch",
    "numpy>=1.26.0,<2.0.0",
    "tqdm",
    "more-itertools",
    "transformers>=4.27.2",
    "ffmpeg-python==0.2.0",
    "click",
    "pyaudio",
    "pydub",
    "SpeechRecognition",
    "python-dotenv",
    "openai-whisper @ git+https://github.com/openai/whisper.git",
    "sounddevice",
    "keyboard",
    "pywin32; sys_platform == 'win32'",
    "googletrans==4.0.0-rc1",
    "numba",
    "soundcard",
    "soundfile",
]

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchvision = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }